linters-settings:
  gci:
    sections:
      - standard
      - prefix(github.com)
      - prefix(golang.org)
      - prefix(go.uber.org/mock)

linters:
  enable:
    # Enabled by Default.
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    # Carians requirements
    - gci
    - revive