version: "2"
linters:
  enable:
    - revive
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
  settings:
    gci:
      sections:
        - standard
        - prefix(github.com)
        - prefix(golang.org)
        - prefix(go.uber.org/mock)
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
