// Code generated by MockGen. DO NOT EDIT.
// Source: file.go

// Package mock_mod is a generated GoMock package.
package mock_mod

import (
	gomock "github.com/golang/mock/gomock"
	mod "github.com/rvflash/goup/internal/mod"
	reflect "reflect"
)

// MockMod is a mock of Mod interface
type MockMod struct {
	ctrl     *gomock.Controller
	recorder *MockModMockRecorder
}

// MockModMockRecorder is the mock recorder for MockMod
type MockModMockRecorder struct {
	mock *MockMod
}

// NewMockMod creates a new mock instance
func NewMockMod(ctrl *gomock.Controller) *MockMod {
	mock := &MockMod{ctrl: ctrl}
	mock.recorder = &MockModMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockMod) EXPECT() *MockModMockRecorder {
	return m.recorder
}

// Module mocks base method
func (m *MockMod) Module() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Module")
	ret0, _ := ret[0].(string)
	return ret0
}

// Module indicates an expected call of Module
func (mr *MockModMockRecorder) Module() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Module", reflect.TypeOf((*MockMod)(nil).Module))
}

// Dependencies mocks base method
func (m *MockMod) Dependencies() []mod.Module {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dependencies")
	ret0, _ := ret[0].([]mod.Module)
	return ret0
}

// Dependencies indicates an expected call of Dependencies
func (mr *MockModMockRecorder) Dependencies() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dependencies", reflect.TypeOf((*MockMod)(nil).Dependencies))
}
